import Head from "next/head";
import Image from "next/image";
import BannerSection from "../components/home banner/banner.component";
import CardsComponent from "../components/home cards/cards.component";
import ChooseDesignComponent from "../components/home chooseDesign/chooseDesign.component";
import LaunchComponent from "../components/home launch/launch.component";
import SectionsViewComponent from "../components/home sectionsView/sectionsView.components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>b7r.store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <BannerSection />
        <LaunchComponent />
        <CardsComponent />
        <ChooseDesignComponent />
        <SectionsViewComponent />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
