import Head from 'next/head'
import Image from 'next/image'
import BannerSection from '../components/home banner/banner.component'
import CardsComponent from '../components/home cards/cards.component'
import ChooseDesignComponent from '../components/home chooseDesign/chooseDesign.component'
import LaunchComponent from '../components/home launch/launch.component'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>b7r.store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <BannerSection/>
        <LaunchComponent/>
        <CardsComponent/>
        <ChooseDesignComponent/>
        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
